export const gldIssuesConfig = {
  githubIssueCategories: [//GitHub Issue labels that populate category filters and progress bars
    "Targets",
    "Website - GTM",
    "Website - content",
    "Website - loyalty",
    "Website - CLP",
    "Website - PDP",
    "Website - Core Web Vitals",
    "Website - UX",
    "Website - SEO",
    "Website - Accessibility",
    "Website - AB Testing",
    "Website - security",
    "SFCC - fix",
    "SFCC - workflow",
    "Dev 2.0 - fix",
    "Dev 2.0 - testing / QA",
    "Dev 2.0 - build tools",
    "Dev 2.0 - collaboration",
    "Dev 2.0 - project management",
    "Dev 2.0 - reporting",
    "Dev 2.0 - helpdesk",
  ],
};
